language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dickfennema/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dickfennema/docker-react npm run test -- --coverage